name: eclair-lang
version: 0.2.0
synopsis: "Eclair: an experimental and minimal Datalog that compiles to LLVM."
description: "Eclair: an experimental and minimal Datalog that compiles to LLVM."
homepage: https://github.com/luc-tielen/eclair-lang
license: BSD3
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: Luc Tielen, 2023
category: Compiler
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - cbits/*.dl

flags:
  debug:
    description: Enables stack traces.
    manual: yes
    default: no

dependencies:
  - name: base
    version: ">= 4.7 && < 5"
    mixin:
      - hiding (Prelude)
  - relude == 1.2.*
  - extra == 1.*
  - text == 2.*
  - bytestring == 0.11.*
  - vector == 0.13.*
  - containers == 0.*
  - transformers == 0.*
  - mtl == 2.*
  - mmorph == 1.*
  - exceptions == 0.10.*
  - prettyprinter == 1.7.*
  - prettyprinter-ansi-terminal == 1.*
  - megaparsec == 9.*
  - parser-combinators == 1.3.*
  - souffle-haskell == 4.0.0
  - recursion-schemes == 5.*
  - comonad == 5.*
  - algebraic-graphs == 0.*
  - llvm-codegen # TODO version
  - rock == 0.3.*
  - dependent-sum >= 0.6 && < 1
  - optparse-applicative == 0.16.*
  - diagnose == 2.3.*
  - dlist == 1.*

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ViewPatterns
  - RankNTypes
  - TypeFamilies
  - DataKinds
  - KindSignatures
  - TupleSections
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables
  - PatternSynonyms
  - RecursiveDo

ghc-options:
  - -Wall
  - -Wincomplete-patterns
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++17
  - -D__EMBEDDED_SOUFFLE__
cxx-sources:
  - cbits/*.cpp

when:
  - condition: os(darwin)
    extra-libraries: c++
  - condition: flag(debug)
    dependencies:
      - haskell-stack-trace-plugin == 0.1.3.0
    ghc-options:
      - -fplugin=StackTrace.Plugin

library:
  source-dirs: lib
  cxx-sources: cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
    - condition: false
      other-modules: Paths_eclair_lang

executables:
  eclair:
    main: Main.hs
    source-dirs: src/eclair
    dependencies:
      - eclair-lang
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
      - relude == 1.2.*
      - directory == 1.*
      - process == 1.6.*
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -Wall

  # Separate executable so these dependencies are not always needed for Eclair.
  eclair-lsp-server:
    main: Main.hs
    source-dirs: src/lsp
    dependencies:
      - eclair-lang
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
      - relude == 1.2.*
      - lsp == 1.4.*
      - lsp-types == 1.4.*
      - lens == 5.2.*
      - recursion-schemes == 5.*
      - data-default == 0.7.*
      - aeson
      - hslogger == 1.3.*
      - filepath == 1.4.*
      - directory == 1.*
      - rope-utf16-splay == 0.4.*
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall

benchmarks:
  eclair-benchmarks:
    main: Main.hs
    source-dirs: benchmarks/src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optl -lbenchmark # extra-libraries: benchmark does not work?
      # - -Wall
    extra-lib-dirs:
      - benchmarks/cbits
    dependencies:
      - base >= 4.7 && < 5
      - criterion == 1.*
      - vector == 0.13.*
      - text == 2.*
      - containers == 0.*
      - attoparsec == 0.14.*
      - deepseq == 1.*
      - eclair-haskell == 0.1.*

tests:
  eclair-test:
    main: test.hs
    source-dirs: tests/eclair
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - hedgehog == 1.*
      - filepath == 1.*
      - neat-interpolation == 0.*
      - silently == 1.2.*
      - eclair-lang
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
  eclair-lsp-test:
    main: Main.hs
    source-dirs: tests/lsp
    build-tools: eclair-lsp-server
    dependencies:
      - eclair-lang
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
      - lsp == 1.4.*
      - lsp-types == 1.4.*
      - lsp-test == 0.14.*
      - hspec >= 2.6.1 && < 3.0.0
      - rope-utf16-splay == 0.4.*
