name: eclair-lang
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/luc-tielen/eclair-lang
license: BSD3
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: Luc Tielen, 2022
category: Web
extra-source-files:
  - README.md

flags:
  debug:
    description: Enables stack traces.
    manual: yes
    default: no

dependencies:
  - name: base
    version: ">= 4.7 && < 5"
    mixin:
      - hiding (Prelude)
  - relude == 1.0.*
  - extra == 1.*
  - text == 1.*
  - bytestring == 0.10.*
  - vector == 0.12.*
  - containers == 0.*
  - transformers == 0.*
  - mtl == 2.*
  - mmorph == 1.*
  - exceptions == 0.10.*
  - lens == 5.* # TODO: use microlens? or Optics?
  - prettyprinter == 1.7.*
  - megaparsec == 9.*
  - souffle-haskell == 3.4.0
  - recursion-schemes == 5.*
  - comonad == 5.*
  - algebraic-graphs == 0.*
  - llvm-codegen # TODO version
  - rock == 0.3.*
  - dependent-sum-template == 0.1.*
  - some == 1.*

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ViewPatterns
  - RankNTypes
  - TypeFamilies
  - DataKinds
  - KindSignatures
  - TupleSections
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables

ghc-options:
  #- -Wall TODO turn on again
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++20
  - -D__EMBEDDED_SOUFFLE__
cxx-sources:
  - cbits/*.cpp

when:
  - condition: os(darwin)
    extra-libraries: c++
  - condition: flag(debug)
    dependencies:
      - haskell-stack-trace-plugin == 0.*
    ghc-options:
      - -fplugin=StackTrace.Plugin

library:
  source-dirs: lib
  cxx-sources: cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
    - condition: false
      other-modules: Paths_eclair_lang

executables:
  eclairc:
    main: Main.hs
    source-dirs: src
    dependencies:
      - eclair-lang
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
      - relude == 1.0.*
      - directory == 1.*
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -Wall

tests:
  eclair-test:
    main: test.hs
    source-dirs: tests
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - hedgehog == 1.*
      - filepath == 1.*
      - neat-interpolation == 0.*
      - eclair-lang
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
