name: eclair-lang
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/luc-tielen/eclair-lang
license: BSD3
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: Luc Tielen, 2021
category: Web
extra-source-files:
  - README.md

flags:
  debug:
    description: Enables stack traces.
    manual: yes
    default: no

dependencies:
  - base >= 4.7 && < 5
  - protolude == 0.3.0
  - extra == 1.*
  - text == 1.*
  - vector == 0.12.*
  - containers == 0.*
  - transformers == 0.*
  - mtl == 2.*
  - mmorph == 1.*
  - exceptions == 0.10.*
  - lens == 4.* # TODO: use microlens?
  - prettyprinter == 1.*
  - megaparsec == 9.*
  - souffle-haskell == 3.1.0
  - recursion-schemes == 5.*
  - algebraic-graphs == 0.*
  - llvm-hs == 9.*
  - llvm-hs-pure == 9.*
  - llvm-hs-pretty == 0.9.0.0
  - llvm-hs-combinators == 0.1.*

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - ViewPatterns
  - RankNTypes
  - TypeFamilies
  - DataKinds
  - KindSignatures
  - TupleSections
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++20
  - -D__EMBEDDED_SOUFFLE__
cxx-sources:
  - cbits/*.cpp

when:
  - condition: os(darwin)
    extra-libraries: c++
  - condition: flag(debug)
    dependencies:
      - haskell-stack-trace-plugin == 0.*
    ghc-options:
      - -fplugin=StackTrace.Plugin

library:
  source-dirs: lib
  cxx-sources: cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++

executables:
  eclairc:
    main: Main.hs
    source-dirs: src
    dependencies:
      - eclair-lang
      - base >= 4.7 && < 5
      - protolude == 0.3.0
      - directory == 1.*
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -Wall

tests:
  eclair-test:
    main: test.hs
    source-dirs: tests
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - hedgehog == 1.*
      - filepath == 1.*
      - neat-interpolation == 0.*
      - eclair-lang
